import DataTablePage from "@/components/common/DataTablePage";
import { categories } from "@/data/libraryData";

function TheLoaiList() {
  return (
    <DataTablePage
      columns={[
        { key: "MaTL", label: "MaTL", displayLabel: "Mã thể loại", autoGenerated: true, primaryKey: true, widthValue: 130 },
        { key: "TenTL", label: "TenTL", displayLabel: "Tên thể loại", widthValue: 220 },
      ]}
      entityName="Thể loại"
      rows={categories}
      searchPlaceholder="Tìm mã hoặc tên thể loại..."
      title="Quản lý Thể loại"
    />
  );
}

export default TheLoaiList;
