import DataTablePage from "@/components/common/DataTablePage";
import { libraryCards, readers } from "@/data/libraryData";
import GiaHanTheDialog from "@/pages/thethuvien/components/GiaHanTheDialog";
import { getCardStatus } from "@/pages/thethuvien/theThuVienUtils";
import { createLookup } from "@/utils/lookup";

const readerNames = createLookup(readers, "MaDG", "TenDG");

function TheThuVienList() {
  return (
    <DataTablePage
      columns={[
        { key: "MaThe", label: "MaThe", displayLabel: "Mã thẻ", autoGenerated: true, primaryKey: true, widthValue: 120 },
        {
          key: "MaDG",
          label: "MaDG",
          displayLabel: "Độc giả",
          displayValue: (row) => readerNames[row.MaDG] ?? row.MaDG,
          options: readers.map((reader) => ({ label: `${reader.MaDG} - ${reader.TenDG}`, value: reader.MaDG })),
          widthValue: 190,
        },
        { key: "NgayCap", label: "NgayCap", displayLabel: "Ngày cấp", inputType: "date", widthValue: 140 },
        { key: "NgayHetHan", label: "NgayHetHan", displayLabel: "Ngày hết hạn", inputType: "date", widthValue: 160 },
        {
          key: "TrangThai",
          label: "TrangThai",
          displayLabel: "Trạng thái",
          badge: true,
          displayValue: (row) => getCardStatus(row.NgayHetHan),
          formHidden: true,
          widthValue: 170,
        },
      ]}
      entityName="Thẻ thư viện"
      renderDetailExtra={({ row, updateRow }) => (
        <GiaHanTheDialog onRenew={(NgayHetHan) => updateRow({ NgayHetHan })} row={row} />
      )}
      rows={libraryCards}
      searchPlaceholder="Tìm mã thẻ hoặc độc giả..."
      title="Quản lý Thẻ thư viện"
    />
  );
}

export default TheThuVienList;
