import DataTablePage from "@/components/common/DataTablePage";
import { borrowTickets, employees, readers } from "@/data/libraryData";
import { SachMuonDetail, SachMuonSelector } from "@/pages/muontra/components/SachMuonContent";
import { createLookup } from "@/utils/lookup";

const readerNames = createLookup(readers, "MaDG", "TenDG");
const employeeNames = createLookup(employees, "MaNV", "TenNV");

function MuonTraList() {
  return (
    <DataTablePage
      columns={[
        { key: "MaMT", label: "MaMT", displayLabel: "Mã mượn trả", autoGenerated: true, primaryKey: true, widthValue: 130 },
        {
          key: "MaDG", label: "MaDG", displayLabel: "Độc giả",
          displayValue: (row) => readerNames[row.MaDG] ?? row.MaDG,
          options: readers.map((reader) => ({ label: `${reader.MaDG} - ${reader.TenDG}`, value: reader.MaDG })),
          widthValue: 190,
        },
        {
          key: "MaNV", label: "MaNV", displayLabel: "Nhân viên",
          displayValue: (row) => employeeNames[row.MaNV] ?? row.MaNV,
          options: employees.map((employee) => ({ label: `${employee.MaNV} - ${employee.TenNV}`, value: employee.MaNV })),
          widthValue: 160,
        },
        { key: "NgayMuon", label: "NgayMuon", displayLabel: "Ngày mượn", inputType: "date", widthValue: 140 },
        { key: "HanTra", label: "HanTra", displayLabel: "Hạn trả", inputType: "date", widthValue: 140 },
        {
          key: "TrangThai", label: "TrangThai", displayLabel: "Trạng thái", badge: true,
          options: ["Đang mượn", "Quá hạn", "Đã trả"].map((value) => ({ label: value, value })),
          widthValue: 140,
        },
      ]}
      entityName="Mượn trả"
      renderDetailExtra={({ row, updateRow }) => (
        <SachMuonDetail onReturned={() => updateRow({ TrangThai: "Đã trả" })} row={row} />
      )}
      renderFormExtra={({ row }) => <SachMuonSelector ticketId={row?.MaMT} />}
      rows={borrowTickets}
      searchPlaceholder="Tìm mã mượn trả hoặc độc giả..."
      title="Quản lý Mượn trả"
    />
  );
}

export default MuonTraList;
