import DataTablePage from "@/components/common/DataTablePage";
import { languages } from "@/data/libraryData";

function NgonNguList() {
  return (
    <DataTablePage
      columns={[
        { key: "MaNN", label: "MaNN", displayLabel: "Mã ngôn ngữ", autoGenerated: true, primaryKey: true, widthValue: 130 },
        { key: "TenNN", label: "TenNN", displayLabel: "Tên ngôn ngữ", widthValue: 190 },
      ]}
      entityName="Ngôn ngữ"
      rows={languages}
      searchPlaceholder="Tìm tên ngôn ngữ..."
      title="Quản lý Ngôn ngữ"
    />
  );
}

export default NgonNguList;
