import DataTablePage from "@/components/common/DataTablePage";
import { shelves } from "@/data/libraryData";

function KeSachList() {
  return (
    <DataTablePage
      columns={[
        { key: "MaViTri", label: "MaViTri", displayLabel: "Mã vị trí", autoGenerated: true, primaryKey: true, widthValue: 120 },
        { key: "TenKe", label: "TenKe", displayLabel: "Tên kệ", widthValue: 190 },
        { key: "MoTa", label: "MoTa", displayLabel: "Mô tả", widthValue: 250 },
      ]}
      entityName="Kệ sách"
      rows={shelves}
      searchPlaceholder="Tìm mã kệ hoặc tên kệ..."
      title="Quản lý Kệ sách"
    />
  );
}

export default KeSachList;
