import DataTablePage from "@/components/common/DataTablePage";
import { classes, faculties } from "@/data/libraryData";
import { createLookup } from "@/utils/lookup";

const facultyNames = createLookup(faculties, "MaKhoa", "TenKhoa");

function LopList() {
  return (
    <DataTablePage
      columns={[
        { key: "MaLop", label: "MaLop", displayLabel: "Mã lớp", autoGenerated: true, primaryKey: true, widthValue: 120 },
        { key: "TenLop", label: "TenLop", displayLabel: "Tên lớp", widthValue: 170 },
        {
          key: "MaKhoa",
          label: "MaKhoa",
          displayLabel: "Khoa",
          displayValue: (row) => facultyNames[row.MaKhoa] ?? row.MaKhoa,
          options: faculties.map((faculty) => ({
            label: `${faculty.MaKhoa} - ${faculty.TenKhoa}`,
            value: faculty.MaKhoa,
          })),
          widthValue: 250,
        },
      ]}
      entityName="Lớp"
      rows={classes}
      searchPlaceholder="Tìm mã lớp hoặc tên lớp..."
      title="Quản lý Lớp"
    />
  );
}

export default LopList;
