import DataTablePage from "@/components/common/DataTablePage";
import { faculties } from "@/data/libraryData";

function KhoaList() {
  return (
    <DataTablePage
      columns={[
        { key: "MaKhoa", label: "MaKhoa", displayLabel: "Mã khoa", autoGenerated: true, primaryKey: true, widthValue: 120 },
        { key: "TenKhoa", label: "TenKhoa", displayLabel: "Tên khoa", widthValue: 250 },
      ]}
      entityName="Khoa"
      rows={faculties}
      searchPlaceholder="Tìm mã khoa hoặc tên khoa..."
      title="Quản lý Khoa"
    />
  );
}

export default KhoaList;
