const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const PHONE_PATTERN = /^\d{10,12}$/;

export function getFieldLabel(column) {
  return column?.displayLabel ?? column?.tableLabel ?? column?.label ?? column?.key ?? "Trường dữ liệu";
}

export function validateGenericEntityForm({ columns, formData, isEdit }) {
  const errors = {};
  const formColumns = columns.filter((column) => !column.formHidden);

  formColumns.forEach((column) => {
    if (column.primaryKey && isEdit) return;

    const rawValue = formData.get(column.key);
    const value = typeof rawValue === "string" ? rawValue.trim() : rawValue;
    const label = getFieldLabel(column);
    const isBlank = value === null || value === undefined || value === "";
    const isLockedPrimaryKey = column.primaryKey && (isEdit || column.autoGenerated);
    const isRequired = column.required !== false && !(isEdit && column.requiredOnCreate) && !isLockedPrimaryKey;

    if (isEdit && column.keepExistingWhenBlank && isBlank) return;

    if (isRequired && isBlank) {
      errors[column.key] = `${label} không được để trống.`;
      return;
    }

    if (isBlank) return;

    const customMessage = validateByFieldName(column.key, value, label, column);
    if (customMessage) errors[column.key] = customMessage;
  });

  return errors;
}

export function validateSachForm(formData, options = {}) {
  const { isEdit = false, rows = [], currentMaSach } = options;
  const errors = {};

  const MaSach = formData.get("MaSach")?.trim();
  const MaTG = formData.get("MaTG");
  const MaNXB = formData.get("MaNXB");
  const MaTL = formData.get("MaTL");
  const TenSach = formData.get("TenSach")?.trim();
  const NamXBRaw = formData.get("NamXB");
  const SoLuongRaw = formData.get("SoLuong");
  const MaNN = formData.get("MaNN");
  const MaViTri = formData.get("MaViTri");

  if (!MaSach) {
    errors.MaSach = "Mã sách không được để trống.";
  } else {
    const isDuplicateMaSach = rows.some(
      (item) => item.MaSach === MaSach && item.MaSach !== currentMaSach
    );

    if (!isEdit && isDuplicateMaSach) {
      errors.MaSach = "Mã sách đã tồn tại.";
    }
  }

  if (!TenSach) {
    errors.TenSach = "Tên sách không được để trống.";
  }

  if (!MaTG) {
    errors.MaTG = "Tác giả không được để trống.";
  }

  if (!MaNXB) {
    errors.MaNXB = "Nhà xuất bản không được để trống.";
  }

  if (!MaTL) {
    errors.MaTL = "Thể loại không được để trống.";
  }

  if (!MaNN) {
    errors.MaNN = "Ngôn ngữ không được để trống.";
  }

  if (!MaViTri) {
    errors.MaViTri = "Vị trí/kệ sách không được để trống.";
  }

  if (!NamXBRaw) {
    errors.NamXB = "Năm xuất bản không được để trống.";
  } else {
    const NamXB = Number(NamXBRaw);
    const currentYear = new Date().getFullYear();

    if (!Number.isInteger(NamXB) || NamXB <= 0 || NamXB > currentYear) {
      errors.NamXB = `Năm xuất bản phải là số nguyên từ 1 đến ${currentYear}.`;
    }
  }

  if (!SoLuongRaw && SoLuongRaw !== "0") {
    errors.SoLuong = "Số lượng không được để trống.";
  } else {
    const SoLuong = Number(SoLuongRaw);

    if (!Number.isInteger(SoLuong) || SoLuong < 0) {
      errors.SoLuong = "Số lượng phải là số nguyên không âm.";
    }
  }

  return errors;
}

export function getFirstErrorMessage(errors) {
  return Object.values(errors)[0] ?? "Vui lòng kiểm tra lại thông tin nhập.";
}

export function hasErrors(errors) {
  return Object.keys(errors).length > 0;
}

function validateByFieldName(key, value, label, column) {
  const normalizedKey = key.toLowerCase();
  const currentYear = new Date().getFullYear();

  if (normalizedKey.includes("email") && !EMAIL_PATTERN.test(value)) {
    return `${label} không đúng định dạng. Ví dụ: name@example.com.`;
  }

  if (["sdt", "sđt", "sodienthoai", "sốđiệnthoại", "phone", "dienthoai"].some((part) => normalizedKey.includes(part))) {
    if (!PHONE_PATTERN.test(value)) return `${label} phải gồm 10-12 chữ số.`;
  }

  if (normalizedKey === "user" && /\s/.test(value)) {
    return `${label} không được chứa khoảng trắng.`;
  }

  if (normalizedKey === "pass" && value.length < 6) {
    return `${label} phải có tối thiểu 6 ký tự.`;
  }

  if (column.inputType === "number" || ["namsinh", "namxb", "soluong"].includes(normalizedKey)) {
    const numberValue = Number(value);

    if (Number.isNaN(numberValue)) return `${label} phải là số hợp lệ.`;
    if (normalizedKey === "soluong" && numberValue < 0) return `${label} không được nhỏ hơn 0.`;
    if (["namsinh", "namxb"].includes(normalizedKey) && (numberValue < 1900 || numberValue > currentYear)) {
      return `${label} phải nằm trong khoảng 1900-${currentYear}.`;
    }
  }

  return "";
}
