import DataTablePage from "@/components/common/DataTablePage";
import { authors } from "@/data/libraryData";

function TacGiaList() {
  return (
    <DataTablePage
      columns={[
        { key: "MaTG", label: "MaTG", displayLabel: "Mã tác giả", autoGenerated: true, primaryKey: true, widthValue: 120 },
        { key: "TenTG", label: "TenTG", displayLabel: "Tên tác giả", widthValue: 220 },
      ]}
      entityName="Tác giả"
      rows={authors}
      searchPlaceholder="Tìm mã hoặc tên tác giả..."
      title="Quản lý Tác giả"
    />
  );
}

export default TacGiaList;
