import DataTablePage from "@/components/common/DataTablePage";
import { classes, faculties, readers } from "@/data/libraryData";
import { createLookup } from "@/utils/lookup";

const facultyNames = createLookup(faculties, "MaKhoa", "TenKhoa");
const classNames = createLookup(classes, "MaLop", "TenLop");

function DocGiaList() {
  return (
    <DataTablePage
      columns={[
        { key: "MaDG", label: "MaDG", tableLabel: "Mã ĐG", displayLabel: "Mã độc giả", autoGenerated: true, primaryKey: true, widthValue: 92 },
        { key: "TenDG", label: "TenDG", tableLabel: "Độc giả", displayLabel: "Tên độc giả", widthValue: 118 },
        {
          key: "MaKhoa",
          label: "MaKhoa",
          displayLabel: "Khoa",
          displayValue: (row) => facultyNames[row.MaKhoa] ?? row.MaKhoa,
          options: faculties.map((faculty) => ({
            label: `${faculty.MaKhoa} - ${faculty.TenKhoa}`,
            value: faculty.MaKhoa,
          })),
          widthValue: 118,
        },
        {
          key: "MaLop",
          label: "MaLop",
          displayLabel: "Lớp",
          displayValue: (row) => classNames[row.MaLop] ?? row.MaLop,
          options: classes.map((classItem) => ({
            label: `${classItem.MaLop} - ${classItem.TenLop}`,
            value: classItem.MaLop,
          })),
          widthValue: 92,
        },
        { key: "NamSinh", label: "NamSinh", tableLabel: "Năm sinh", displayLabel: "Năm sinh", widthValue: 82 },
        {
          key: "GioiTinh",
          label: "GioiTinh",
          tableLabel: "GT",
          displayLabel: "Giới tính",
          options: [
            { label: "Nam", value: "Nam" },
            { label: "Nữ", value: "Nữ" },
            { label: "Khác", value: "Khác" },
          ],
          widthValue: 64,
        },
        { key: "DiaChi", label: "DiaChi", displayLabel: "Địa chỉ", widthValue: 112 },
        { key: "Email", label: "Email", displayLabel: "Email", widthValue: 118 },
        { key: "Sdt", label: "Sdt", tableLabel: "SĐT", displayLabel: "Số điện thoại", widthValue: 96 },
      ]}
      entityName="Độc giả"
      rows={readers}
      searchPlaceholder="Tìm mã, tên hoặc số điện thoại..."
      title="Quản lý Độc giả"
    />
  );
}

export default DocGiaList;
